language: python
python:
  - "3.5"
install: 
  - pip install -r requirements.txt
script:
  - coverage run --source . testrunner.py --testpath ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
