"""Fix typo Team

Revision ID: 0a43889324ab
Revises: d2853477b461
Create Date: 2017-01-04 17:27:56.392209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43889324ab'
down_revision = 'd2853477b461'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_teams', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_teams_team_ud_fkey', 'users_teams', type_='foreignkey')
    op.create_foreign_key(None, 'users_teams', 'teams', ['team_id'], ['id'])
    op.drop_column('users_teams', 'team_ud')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_teams', sa.Column('team_ud', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users_teams', type_='foreignkey')
    op.create_foreign_key('users_teams_team_ud_fkey', 'users_teams', 'teams', ['team_ud'], ['id'])
    op.drop_column('users_teams', 'team_id')
    ### end Alembic commands ###
