"""remove pk from users_teams

Revision ID: 9504fa232ac8
Revises: edd56951650c
Create Date: 2017-01-21 19:27:39.776288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9504fa232ac8'
down_revision = 'edd56951650c'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_teams', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_teams', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
