"""Add project table

Revision ID: c5bc52d73cec
Revises: 917f9e1719dd
Create Date: 2016-11-20 22:10:53.183220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc52d73cec'
down_revision = '917f9e1719dd'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    ### end Alembic commands ###
