"""Add user-project relationship

Revision ID: e9f89fb022ef
Revises: c5bc52d73cec
Create Date: 2016-12-25 17:47:50.974011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f89fb022ef'
down_revision = 'c5bc52d73cec'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_projects',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('projects', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'name')
    op.drop_table('users_projects')
    ### end Alembic commands ###
